Description:
  Mohamed Awwad >> Final Project Advanced Cloud Track

  A CFN Script to deploy host for Udargam project.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names.
    Type: String
    Default: Udagram

  BastionHostAMI:
    Description: The machine image to be used for bastion host.
    Type: String
    Default: ami-03190fe20ef6b1419
  
  BastionHostInstanceType:
    Description: The host EC2 instance type to be used. 
    Type: String
    Default: t3.micro

  BastionHostKeyName:
    Description: Name of an existing KeyPair to enable SSH access to the web servers from bastion host.
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: udagramprojects
  
  LocalHostIP:
    Description: localhost IP that used to ssh the instance.
    Type: String
    Default: 1.2.3.4/32

Resources:
  BastionHostFullSSM:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/AmazonSSMFullAccess"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: "/"
  
  BastionHostSecGroup: 
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      GroupDescription: "Allow SSH access via port 22 to web servers"
      VpcId: 
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"  
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref LocalHostIP

  BastionHost1: 
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref BastionHostAMI 
      InstanceType: !Ref BastionHostInstanceType
      IamInstanceProfile: !Ref ProfileWithRolesForBastion
      SecurityGroupIds: 
        - !Ref BastionHostSecGroup
      KeyName: !Ref BastionHostKeyName
      SubnetId: 
        Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip python3-pip apache2 awscli -y
          systemctl start apache2.service
          snap start amazon-ssm-agent
          pip3 install --upgrade awscli
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          dpkg -i session-manager-plugin.deb
    DependsOn:
      - BastionHostSecGroup
      - ProfileWithRolesForBastion

  EIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: 
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"      

  EIPAssociation1:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId:
        Ref: BastionHost1
      AllocationId: !GetAtt EIP1.AllocationId
    DependsOn:
      - BastionHost1
      - EIP1

  BastionHost2: 
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref BastionHostAMI 
      InstanceType: !Ref BastionHostInstanceType
      IamInstanceProfile: !Ref ProfileWithRolesForBastion
      SecurityGroupIds: 
        - !Ref BastionHostSecGroup
      KeyName: !Ref BastionHostKeyName
      SubnetId: 
        Fn::ImportValue: !Sub "${EnvironmentName}-PUB2-SN"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip python3-pip apache2 awscli -y
          systemctl start apache2.service
          snap start amazon-ssm-agent
          pip3 install --upgrade awscli
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          dpkg -i session-manager-plugin.deb
    DependsOn:
      - BastionHostSecGroup
      - ProfileWithRolesForBastion

  EIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: 
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"      

  EIPAssociation2:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId:
        Ref: BastionHost2
      AllocationId: !GetAtt EIP2.AllocationId
    DependsOn:
      - BastionHost2
      - EIP2

Outputs:
  BastionHost1CIDR:
    Description: A reference to the Bastion Host 1 CIDR.
    Value: 
      !Join
        - ''
        - - !GetAtt BastionHost1.PrivateIp
          - !Sub '/32'
    Export:
        Name: !Sub ${EnvironmentName}-BASTION-HOST-1-CIDR

  BastionHost2CIDR:
    Description: A reference to the Bastion Host 2 CIDR.
    Value: 
      !Join
        - ''
        - - !GetAtt BastionHost2.PrivateIp
          - !Sub '/32'
    Export:
        Name: !Sub ${EnvironmentName}-BASTION-HOST-2-CIDR 